import type { IrregularVerb } from "./verbs.js";

export type VerbForm = "pastSimple" | "pastParticiple";
export const VERB_FORMS: readonly VerbForm[] = [
  "pastSimple",
  "pastParticiple",
];

export type VerbContext = {
  form: VerbForm;
  sentence: string;
};

export type VerbContextSet = Record<VerbForm, string>;

// One hand-written example for every verb, practising either past simple or
// past participle in context.
export const VERB_CONTEXTS: Record<string, VerbContext> = {
  arise: { form: "pastSimple", sentence: "Several problems ____ during yesterday's meeting." },
  awake: { form: "pastSimple", sentence: "She ____ before sunrise and went for a run." },
  be: { form: "pastParticiple", sentence: "He has ____ very patient with the new students." },
  bear: { form: "pastSimple", sentence: "She ____ the pain without complaining." },
  beat: { form: "pastSimple", sentence: "Our team ____ the champions in the final." },
  become: { form: "pastParticiple", sentence: "The neighborhood has ____ much quieter recently." },
  begin: { form: "pastSimple", sentence: "The ceremony ____ at six o'clock." },
  bend: { form: "pastSimple", sentence: "He ____ the wire into a circle." },
  bet: { form: "pastParticiple", sentence: "I have never ____ money on a football match." },
  bid: { form: "pastSimple", sentence: "Several collectors ____ for the painting yesterday." },
  bind: { form: "pastSimple", sentence: "She ____ the papers together with string." },
  bite: { form: "pastParticiple", sentence: "The dog has never ____ anyone." },
  bleed: { form: "pastSimple", sentence: "The small cut ____ for several minutes." },
  blow: { form: "pastSimple", sentence: "The wind ____ the gate open last night." },
  break: { form: "pastParticiple", sentence: "Someone has ____ the handle on the door." },
  breed: { form: "pastSimple", sentence: "These birds ____ near the coast last spring." },
  bring: { form: "pastSimple", sentence: "Maya ____ homemade bread to the picnic." },
  build: { form: "pastParticiple", sentence: "They have ____ a new bridge across the river." },
  burn: { form: "pastSimple", sentence: "The dry leaves ____ very quickly." },
  burst: { form: "pastSimple", sentence: "The balloon ____ when it touched the candle." },
  buy: { form: "pastParticiple", sentence: "We have ____ enough food for the weekend." },
  cast: { form: "pastSimple", sentence: "The tall buildings ____ long shadows yesterday evening." },
  catch: { form: "pastSimple", sentence: "I ____ the last bus home." },
  choose: { form: "pastParticiple", sentence: "They have ____ a quiet place for the meeting." },
  cling: { form: "pastSimple", sentence: "The wet clothes ____ to his skin." },
  come: { form: "pastSimple", sentence: "Her cousins ____ to visit us yesterday." },
  cost: { form: "pastParticiple", sentence: "The repairs have ____ more than we expected." },
  creep: { form: "pastSimple", sentence: "The cat ____ quietly toward the bird." },
  cut: { form: "pastSimple", sentence: "Leo ____ the cake into eight pieces." },
  deal: { form: "pastParticiple", sentence: "She has ____ with similar problems before." },
  dig: { form: "pastSimple", sentence: "We ____ a hole for the tree yesterday." },
  do: { form: "pastSimple", sentence: "They ____ all the work before lunch." },
  draw: { form: "pastParticiple", sentence: "The artist has ____ a portrait of her grandmother." },
  drink: { form: "pastSimple", sentence: "She ____ plenty of water after the race." },
  drive: { form: "pastSimple", sentence: "Sam ____ through the night to reach the coast." },
  eat: { form: "pastParticiple", sentence: "The children have ____ all the strawberries." },
  fall: { form: "pastSimple", sentence: "Temperatures ____ below zero last night." },
  feed: { form: "pastSimple", sentence: "Nora ____ the horses early this morning." },
  feel: { form: "pastParticiple", sentence: "I have ____ much better since the weekend." },
  fight: { form: "pastSimple", sentence: "The two armies ____ for control of the city." },
  find: { form: "pastSimple", sentence: "We ____ your keys under the sofa." },
  flee: { form: "pastParticiple", sentence: "Many residents had ____ before the storm arrived." },
  fling: { form: "pastSimple", sentence: "He ____ his coat onto the floor." },
  fly: { form: "pastSimple", sentence: "The geese ____ south at the end of summer." },
  forbid: { form: "pastParticiple", sentence: "The school has ____ phones during examinations." },
  forget: { form: "pastSimple", sentence: "I ____ to lock the back door yesterday." },
  forgive: { form: "pastSimple", sentence: "She ____ him after he apologized sincerely." },
  freeze: { form: "pastParticiple", sentence: "The lake has ____ completely overnight." },
  get: { form: "pastSimple", sentence: "I ____ some milk on the way home." },
  give: { form: "pastSimple", sentence: "Our teacher ____ us extra time to finish." },
  go: { form: "pastParticiple", sentence: "The last train has already ____." },
  grind: { form: "pastSimple", sentence: "He ____ the coffee beans before breakfast." },
  grow: { form: "pastSimple", sentence: "The children ____ very quickly last year." },
  have: { form: "pastParticiple", sentence: "We have ____ several chances to discuss the plan." },
  hear: { form: "pastSimple", sentence: "We ____ the sea from our balcony last night." },
  hide: { form: "pastSimple", sentence: "The child ____ behind the curtains." },
  hit: { form: "pastParticiple", sentence: "The storm has ____ the northern coast badly." },
  hold: { form: "pastSimple", sentence: "She ____ the door open for me." },
  hurt: { form: "pastSimple", sentence: "I ____ my shoulder while lifting the box." },
  input: { form: "pastParticiple", sentence: "The technician has ____ all the customer data." },
  keep: { form: "pastSimple", sentence: "They ____ the information confidential." },
  know: { form: "pastSimple", sentence: "I ____ the answer as soon as I saw the question." },
  lay: { form: "pastParticiple", sentence: "The workers have ____ new tiles in the kitchen." },
  lead: { form: "pastSimple", sentence: "The narrow path ____ us back to the village." },
  leave: { form: "pastSimple", sentence: "They ____ their umbrellas at the restaurant." },
  lend: { form: "pastParticiple", sentence: "My sister has ____ me her bicycle for the week." },
  let: { form: "pastSimple", sentence: "She ____ me know when she arrived." },
  lie: { form: "pastSimple", sentence: "The cat ____ in the sun all afternoon." },
  light: { form: "pastParticiple", sentence: "Someone has ____ a fire in the fireplace." },
  lose: { form: "pastSimple", sentence: "He ____ his passport at the airport." },
  make: { form: "pastSimple", sentence: "Amir ____ a delicious soup for dinner." },
  mean: { form: "pastParticiple", sentence: "This symbol has always ____ good luck." },
  meet: { form: "pastSimple", sentence: "We ____ outside the station at noon." },
  mistake: { form: "pastSimple", sentence: "I ____ his brother for him in the crowd." },
  pay: { form: "pastParticiple", sentence: "She has already ____ the electricity bill." },
  prove: { form: "pastSimple", sentence: "The evidence ____ that he was elsewhere." },
  put: { form: "pastSimple", sentence: "I ____ your package on the kitchen table." },
  quit: { form: "pastParticiple", sentence: "He has ____ drinking coffee in the evening." },
  read: { form: "pastSimple", sentence: "I ____ for an hour before bed last night." },
  rid: { form: "pastSimple", sentence: "They ____ the garden of weeds last weekend." },
  ride: { form: "pastParticiple", sentence: "She has ____ a horse only once." },
  ring: { form: "pastSimple", sentence: "I ____ the bell when everyone was ready." },
  rise: { form: "pastSimple", sentence: "The river ____ rapidly after the heavy rain." },
  run: { form: "pastParticiple", sentence: "He has ____ three marathons this year." },
  say: { form: "pastSimple", sentence: "She ____ nothing about the delay." },
  see: { form: "pastSimple", sentence: "We ____ dolphins near the boat." },
  seek: { form: "pastParticiple", sentence: "The company has ____ advice from several experts." },
  sell: { form: "pastSimple", sentence: "They ____ their old apartment last month." },
  send: { form: "pastSimple", sentence: "I ____ the documents by email yesterday." },
  set: { form: "pastParticiple", sentence: "They have ____ a date for the wedding." },
  shake: { form: "pastSimple", sentence: "He ____ the bottle before opening it." },
  shave: { form: "pastSimple", sentence: "He ____ his beard before the interview." },
  shed: { form: "pastParticiple", sentence: "The old tree has ____ most of its leaves." },
  shine: { form: "pastSimple", sentence: "The stars ____ brightly last night." },
  shoot: { form: "pastSimple", sentence: "The photographer ____ hundreds of pictures at the event." },
  show: { form: "pastParticiple", sentence: "The results have ____ a clear improvement." },
  shrink: { form: "pastSimple", sentence: "The sweater ____ when I washed it in hot water." },
  shut: { form: "pastSimple", sentence: "She ____ all the windows before the storm." },
  sing: { form: "pastParticiple", sentence: "They have ____ together since they were children." },
  sink: { form: "pastSimple", sentence: "The heavy stone ____ quickly in the deep water." },
  sit: { form: "pastSimple", sentence: "We ____ beside the lake and watched the sunset." },
  slay: { form: "pastParticiple", sentence: "The hero had ____ the dragon before dawn." },
  sleep: { form: "pastSimple", sentence: "I ____ for eight hours last night." },
  slide: { form: "pastSimple", sentence: "The glass ____ off the tray and broke." },
  sling: { form: "pastParticiple", sentence: "He had ____ his jacket over one shoulder." },
  slit: { form: "pastSimple", sentence: "He ____ the envelope open with a sharp knife." },
  sow: { form: "pastSimple", sentence: "The farmers ____ wheat in the eastern field." },
  speak: { form: "pastParticiple", sentence: "I have ____ to the manager about the issue." },
  speed: { form: "pastSimple", sentence: "The driver ____ through the village." },
  spell: { form: "pastSimple", sentence: "She ____ my surname correctly on the first try." },
  spend: { form: "pastParticiple", sentence: "We have ____ too much money this month." },
  spin: { form: "pastSimple", sentence: "The wheels ____ faster as the bicycle went downhill." },
  spit: { form: "pastSimple", sentence: "The baby ____ out the medicine immediately." },
  split: { form: "pastParticiple", sentence: "They have ____ the class into four groups." },
  spread: { form: "pastSimple", sentence: "She ____ the map across the table." },
  spring: { form: "pastSimple", sentence: "The cat ____ onto the windowsill." },
  stand: { form: "pastParticiple", sentence: "We have ____ in this queue for nearly an hour." },
  steal: { form: "pastSimple", sentence: "Someone ____ the unlocked bicycle yesterday." },
  stick: { form: "pastSimple", sentence: "I ____ the notice on the office door yesterday." },
  sting: { form: "pastParticiple", sentence: "A bee has ____ me on the hand." },
  stink: { form: "pastSimple", sentence: "Those old shoes really ____ after the long walk." },
  strike: { form: "pastSimple", sentence: "Lightning ____ the old oak tree during the storm." },
  swear: { form: "pastParticiple", sentence: "He has ____ never to reveal the secret." },
  sweep: { form: "pastSimple", sentence: "She ____ the kitchen floor after dinner." },
  swell: { form: "pastSimple", sentence: "Her ankle ____ after the long hike." },
  swim: { form: "pastParticiple", sentence: "They have ____ across the bay several times." },
  swing: { form: "pastSimple", sentence: "The doors ____ open when he pressed the button." },
  take: { form: "pastSimple", sentence: "Mina ____ the children to the science museum." },
  teach: { form: "pastParticiple", sentence: "Mr. Lee has ____ at this school for twenty years." },
  tear: { form: "pastSimple", sentence: "The child ____ the thin paper accidentally." },
  tell: { form: "pastSimple", sentence: "She ____ us a funny story on the journey." },
  think: { form: "pastParticiple", sentence: "I have ____ carefully about your proposal." },
  throw: { form: "pastSimple", sentence: "She ____ the ball back to me." },
  thrust: { form: "pastSimple", sentence: "He ____ the letter into my hand and hurried away." },
  wake: { form: "pastParticiple", sentence: "The loud thunder has ____ the baby." },
  wear: { form: "pastSimple", sentence: "He ____ comfortable shoes for the walk." },
  weep: { form: "pastSimple", sentence: "She ____ with relief when she heard the news." },
  win: { form: "pastParticiple", sentence: "Our school has ____ the competition twice." },
  wind: { form: "pastSimple", sentence: "She ____ the old clock on Sunday." },
  write: { form: "pastSimple", sentence: "I ____ her address on a piece of paper." },
};

const ADDITIONAL_VERB_CONTEXTS: Record<string, VerbContext> = {
  arise: { form: "pastParticiple", sentence: "A serious problem has ____ with the new schedule." },
  awake: { form: "pastParticiple", sentence: "The noise has ____ everyone in the house." },
  be: { form: "pastSimple", sentence: "She ____ delighted with the surprise." },
  bear: { form: "pastParticiple", sentence: "The old bridge has ____ the weight for decades." },
  beat: { form: "pastParticiple", sentence: "No team has ____ them this season." },
  become: { form: "pastSimple", sentence: "The sky ____ dark before the rain began." },
  begin: { form: "pastParticiple", sentence: "The concert has already ____." },
  bend: { form: "pastParticiple", sentence: "The strong wind has ____ the young tree." },
  bet: { form: "pastSimple", sentence: "He ____ ten euros on the winning horse." },
  bid: { form: "pastParticiple", sentence: "A collector has ____ a thousand euros for the vase." },
  bind: { form: "pastParticiple", sentence: "The agreement has ____ the two companies together." },
  bite: { form: "pastSimple", sentence: "A mosquito ____ me during the night." },
  bleed: { form: "pastParticiple", sentence: "His injured hand has ____ through the bandage." },
  blow: { form: "pastParticiple", sentence: "The wind has ____ all the leaves away." },
  break: { form: "pastSimple", sentence: "Ella ____ her glasses at school." },
  breed: { form: "pastParticiple", sentence: "The farm has ____ sheep for many years." },
  bring: { form: "pastParticiple", sentence: "You have ____ exactly what we needed." },
  build: { form: "pastSimple", sentence: "They ____ the cabin beside the lake." },
  burn: { form: "pastParticiple", sentence: "The toast has ____ around the edges." },
  burst: { form: "pastParticiple", sentence: "One of the water pipes has ____." },
  buy: { form: "pastSimple", sentence: "We ____ fresh vegetables at the market." },
  cast: { form: "pastParticiple", sentence: "The lamp has ____ a warm glow across the room." },
  catch: { form: "pastParticiple", sentence: "She has ____ every ball so far." },
  choose: { form: "pastSimple", sentence: "I ____ the blue jacket instead of the black one." },
  cling: { form: "pastParticiple", sentence: "The child has ____ to her mother all morning." },
  come: { form: "pastParticiple", sentence: "Everyone has ____ to celebrate her birthday." },
  cost: { form: "pastSimple", sentence: "The new laptop ____ less than I expected." },
  creep: { form: "pastParticiple", sentence: "Fog has ____ across the valley." },
  cut: { form: "pastParticiple", sentence: "I have ____ the vegetables for the soup." },
  deal: { form: "pastSimple", sentence: "The manager ____ with the complaint calmly." },
  dig: { form: "pastParticiple", sentence: "The dog has ____ a hole under the fence." },
  do: { form: "pastParticiple", sentence: "I have ____ everything on the checklist." },
  draw: { form: "pastSimple", sentence: "The child ____ a castle on the board." },
  drink: { form: "pastParticiple", sentence: "They have ____ all the orange juice." },
  drive: { form: "pastParticiple", sentence: "I have ____ this route many times." },
  eat: { form: "pastSimple", sentence: "We ____ lunch in the garden." },
  fall: { form: "pastParticiple", sentence: "Several branches have ____ onto the road." },
  feed: { form: "pastParticiple", sentence: "Have you ____ the cat today?" },
  feel: { form: "pastSimple", sentence: "She ____ nervous before the interview." },
  fight: { form: "pastParticiple", sentence: "They have ____ hard to protect the forest." },
  find: { form: "pastParticiple", sentence: "Scientists have ____ a safer solution." },
  flee: { form: "pastSimple", sentence: "The deer ____ when it heard us approaching." },
  fling: { form: "pastParticiple", sentence: "Someone has ____ the door wide open." },
  fly: { form: "pastParticiple", sentence: "She has ____ across the Atlantic twice." },
  forbid: { form: "pastSimple", sentence: "The doctor ____ him from lifting heavy objects." },
  forget: { form: "pastParticiple", sentence: "I have ____ where I left my keys." },
  forgive: { form: "pastParticiple", sentence: "They have ____ each other at last." },
  freeze: { form: "pastSimple", sentence: "The pipes ____ during the cold night." },
  get: { form: "pastParticiple", sentence: "The weather has ____ much warmer." },
  give: { form: "pastParticiple", sentence: "They have ____ us a warm welcome." },
  go: { form: "pastSimple", sentence: "We ____ to the beach after breakfast." },
  grind: { form: "pastParticiple", sentence: "She has ____ the spices into a fine powder." },
  grow: { form: "pastParticiple", sentence: "The tomato plants have ____ very tall." },
  have: { form: "pastSimple", sentence: "I ____ a headache after the long journey." },
  hear: { form: "pastParticiple", sentence: "We have ____ that story many times." },
  hide: { form: "pastParticiple", sentence: "Someone has ____ the remote control." },
  hit: { form: "pastSimple", sentence: "The ball ____ the window and cracked it." },
  hold: { form: "pastParticiple", sentence: "This hall has ____ many important events." },
  hurt: { form: "pastParticiple", sentence: "The harsh criticism has ____ his confidence." },
  input: { form: "pastSimple", sentence: "She ____ the figures into the database." },
  keep: { form: "pastParticiple", sentence: "I have ____ every letter you sent me." },
  know: { form: "pastParticiple", sentence: "We have ____ each other since childhood." },
  lay: { form: "pastSimple", sentence: "The hen ____ three eggs yesterday." },
  lead: { form: "pastParticiple", sentence: "Her research has ____ to an important discovery." },
  leave: { form: "pastParticiple", sentence: "Someone has ____ a message on your desk." },
  lend: { form: "pastSimple", sentence: "Ben ____ me his camera for the trip." },
  let: { form: "pastParticiple", sentence: "They have ____ us use their garden." },
  lie: { form: "pastParticiple", sentence: "The book has ____ unopened for years." },
  light: { form: "pastSimple", sentence: "She ____ a candle during the power cut." },
  lose: { form: "pastParticiple", sentence: "Our team has ____ only one match this year." },
  make: { form: "pastParticiple", sentence: "He has ____ a wooden table by hand." },
  mean: { form: "pastSimple", sentence: "I ____ every word of my apology." },
  meet: { form: "pastParticiple", sentence: "Have you ____ our new neighbors yet?" },
  mistake: { form: "pastParticiple", sentence: "She has ____ politeness for friendship." },
  pay: { form: "pastSimple", sentence: "We ____ for the tickets online." },
  prove: { form: "pastParticiple", sentence: "The new treatment has ____ effective." },
  put: { form: "pastParticiple", sentence: "I have ____ clean towels in your room." },
  quit: { form: "pastSimple", sentence: "She ____ her job to travel abroad." },
  read: { form: "pastParticiple", sentence: "He has ____ every book in the series." },
  rid: { form: "pastParticiple", sentence: "We have ____ the house of unwanted furniture." },
  ride: { form: "pastSimple", sentence: "They ____ their bicycles along the coast." },
  ring: { form: "pastParticiple", sentence: "The church bells have ____ all morning." },
  rise: { form: "pastParticiple", sentence: "Food prices have ____ sharply this year." },
  run: { form: "pastSimple", sentence: "He ____ home before the rain started." },
  say: { form: "pastParticiple", sentence: "They have ____ everything that needs to be said." },
  see: { form: "pastParticiple", sentence: "I have never ____ such a bright rainbow." },
  seek: { form: "pastSimple", sentence: "She ____ help from a financial adviser." },
  sell: { form: "pastParticiple", sentence: "The shop has ____ all its winter coats." },
  send: { form: "pastParticiple", sentence: "We have ____ invitations to fifty guests." },
  set: { form: "pastSimple", sentence: "He ____ the alarm for seven o'clock." },
  shake: { form: "pastParticiple", sentence: "The explosion has ____ the whole building." },
  shave: { form: "pastParticiple", sentence: "He has ____ off his beard." },
  shed: { form: "pastSimple", sentence: "The dog ____ hair all over the sofa." },
  shine: { form: "pastParticiple", sentence: "The sun has ____ all afternoon." },
  shoot: { form: "pastParticiple", sentence: "The director has ____ the final scene." },
  show: { form: "pastSimple", sentence: "The guide ____ us the oldest part of the city." },
  shrink: { form: "pastParticiple", sentence: "My jeans have ____ in the wash." },
  shut: { form: "pastParticiple", sentence: "They have ____ the road because of flooding." },
  sing: { form: "pastSimple", sentence: "The choir ____ beautifully at the ceremony." },
  sink: { form: "pastParticiple", sentence: "The boat has ____ to the bottom of the harbor." },
  sit: { form: "pastParticiple", sentence: "She has ____ at that desk all day." },
  slay: { form: "pastSimple", sentence: "The legendary knight ____ the monster." },
  sleep: { form: "pastParticiple", sentence: "The baby has ____ peacefully all afternoon." },
  slide: { form: "pastParticiple", sentence: "The keys have ____ behind the cabinet." },
  sling: { form: "pastSimple", sentence: "She ____ the bag across her shoulder." },
  slit: { form: "pastParticiple", sentence: "Someone has ____ the fabric down the middle." },
  sow: { form: "pastParticiple", sentence: "We have ____ wildflower seeds along the path." },
  speak: { form: "pastSimple", sentence: "He ____ confidently during the presentation." },
  speed: { form: "pastParticiple", sentence: "The car has ____ past us twice today." },
  spell: { form: "pastParticiple", sentence: "You have ____ my name incorrectly." },
  spend: { form: "pastSimple", sentence: "They ____ the weekend in the mountains." },
  spin: { form: "pastParticiple", sentence: "The dancer has ____ across the entire stage." },
  spit: { form: "pastParticiple", sentence: "The machine has ____ the card back out." },
  split: { form: "pastSimple", sentence: "We ____ the bill equally among four people." },
  spread: { form: "pastParticiple", sentence: "News of the discovery has ____ quickly." },
  spring: { form: "pastParticiple", sentence: "Several flowers have ____ from the rocky ground." },
  stand: { form: "pastSimple", sentence: "She ____ near the entrance and waited." },
  steal: { form: "pastParticiple", sentence: "Someone has ____ my wallet." },
  stick: { form: "pastParticiple", sentence: "I have ____ up a lot of posters in my room." },
  sting: { form: "pastSimple", sentence: "A wasp ____ him on the neck." },
  stink: { form: "pastParticiple", sentence: "The rubbish has ____ all week." },
  strike: { form: "pastParticiple", sentence: "A powerful earthquake has ____ the region." },
  swear: { form: "pastSimple", sentence: "She ____ that she had told the truth." },
  sweep: { form: "pastParticiple", sentence: "They have ____ the path clear of leaves." },
  swell: { form: "pastParticiple", sentence: "The river has ____ after days of rain." },
  swim: { form: "pastSimple", sentence: "We ____ across the lake before breakfast." },
  swing: { form: "pastParticiple", sentence: "The gate has ____ shut in the wind." },
  take: { form: "pastParticiple", sentence: "Someone has ____ my seat." },
  teach: { form: "pastSimple", sentence: "She ____ us how to make bread." },
  tear: { form: "pastParticiple", sentence: "The sharp branch has ____ my jacket." },
  tell: { form: "pastParticiple", sentence: "I have ____ you everything I know." },
  think: { form: "pastSimple", sentence: "We ____ the shop would still be open." },
  throw: { form: "pastParticiple", sentence: "They have ____ away the broken chairs." },
  thrust: { form: "pastParticiple", sentence: "The sudden crisis has ____ her into the spotlight." },
  wake: { form: "pastSimple", sentence: "I ____ before my alarm this morning." },
  wear: { form: "pastParticiple", sentence: "She has ____ that necklace for years." },
  weep: { form: "pastParticiple", sentence: "He has ____ openly about the loss." },
  win: { form: "pastSimple", sentence: "Our team ____ the regional championship." },
  wind: { form: "pastParticiple", sentence: "The path has ____ through the hills for miles." },
  write: { form: "pastParticiple", sentence: "She has ____ three chapters this week." },
};

export function getVerbContexts(verb: IrregularVerb): VerbContextSet {
  const primary = VERB_CONTEXTS[verb.base];
  const additional = ADDITIONAL_VERB_CONTEXTS[verb.base];
  if (!primary || !additional) {
    throw new Error(`Missing context sentence for verb: ${verb.base}`);
  }

  if (primary.form === additional.form) {
    throw new Error(`Duplicate context form for verb: ${verb.base}`);
  }

  if (primary.form === "pastSimple") {
    return {
      pastSimple: primary.sentence,
      pastParticiple: additional.sentence,
    };
  }

  return {
    pastSimple: additional.sentence,
    pastParticiple: primary.sentence,
  };
}

export function getVerbContext(
  verb: IrregularVerb,
  form: VerbForm
): VerbContext {
  return { form, sentence: getVerbContexts(verb)[form] };
}

export function contextAnswer(verb: IrregularVerb, form: VerbForm): string {
  return verb[form];
}

export function contextFormLabel(form: VerbForm): string {
  switch (form) {
    case "pastSimple":
      return "second form";
    case "pastParticiple":
      return "third form";
  }
}
